# Generated by Django 3.1.5 on 2021-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registoSorteo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros', models.CharField(max_length=2, verbose_name='Numero')),
                ('bolilla', models.CharField(max_length=2, verbose_name='Bolilla')),
            ],
            options={
                'verbose_name': 'registoSorteo',
                'verbose_name_plural': 'registoSorteos',
                'get_latest_by': 'bolilla',
            },
        ),
    ]
