# Generated by Django 3.1.5 on 2021-02-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carton', models.CharField(max_length=7, verbose_name='NumeroCarton')),
                ('celda00', models.CharField(max_length=2, verbose_name='Celda00')),
                ('celda10', models.CharField(max_length=2, verbose_name='Celda10')),
                ('celda20', models.CharField(max_length=2, verbose_name='Celda20')),
                ('celda30', models.CharField(max_length=2, verbose_name='Celda30')),
                ('celda40', models.CharField(max_length=2, verbose_name='Celda40')),
                ('celda50', models.CharField(max_length=2, verbose_name='Celda50')),
                ('celda60', models.CharField(max_length=2, verbose_name='Celda60')),
                ('celda70', models.CharField(max_length=2, verbose_name='Celda70')),
                ('celda80', models.CharField(max_length=2, verbose_name='Celda80')),
                ('celda01', models.CharField(max_length=2, verbose_name='Celda02')),
                ('celda11', models.CharField(max_length=2, verbose_name='Celda02')),
                ('celda21', models.CharField(max_length=2, verbose_name='Celda21')),
                ('celda31', models.CharField(max_length=2, verbose_name='Celda31')),
                ('celda41', models.CharField(max_length=2, verbose_name='Celda41')),
                ('celda51', models.CharField(max_length=2, verbose_name='Celda51')),
                ('celda61', models.CharField(max_length=2, verbose_name='Celda61')),
                ('celda71', models.CharField(max_length=2, verbose_name='Celda71')),
                ('celda81', models.CharField(max_length=2, verbose_name='Celda81')),
                ('celda02', models.CharField(max_length=2, verbose_name='Celda03')),
                ('celda12', models.CharField(max_length=2, verbose_name='Celda22')),
                ('celda22', models.CharField(max_length=2, verbose_name='Celda22')),
                ('celda32', models.CharField(max_length=2, verbose_name='Celda32')),
                ('celda42', models.CharField(max_length=2, verbose_name='Celda42')),
                ('celda52', models.CharField(max_length=2, verbose_name='Celda52')),
                ('celda62', models.CharField(max_length=2, verbose_name='Celda62')),
                ('celda72', models.CharField(max_length=2, verbose_name='Celda72')),
                ('celda82', models.CharField(max_length=2, verbose_name='Celda82')),
            ],
        ),
    ]
