# Generated by Django 3.1.5 on 2021-02-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0003_auto_20210131_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carton',
            options={'get_latest_by': 'numero_carton', 'verbose_name': 'Carton', 'verbose_name_plural': 'Cartones'},
        ),
    ]
