# Generated by Django 3.1.5 on 2021-02-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0005_carton_participante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numeros_sorteados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros', models.CharField(max_length=2, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Numero',
                'verbose_name_plural': 'Numeros',
                'get_latest_by': 'numero',
            },
        ),
    ]
