# Generated by Django 3.1.6 on 2021-02-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0006_numeros_sorteados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numeros_sorteados',
            options={'get_latest_by': 'celda', 'verbose_name': 'Numero', 'verbose_name_plural': 'Numeros'},
        ),
        migrations.RemoveField(
            model_name='numeros_sorteados',
            name='numeros',
        ),
        migrations.AddField(
            model_name='numeros_sorteados',
            name='celda',
            field=models.CharField(default=None, max_length=2, verbose_name='Celda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeros_sorteados',
            name='valor',
            field=models.CharField(default=None, max_length=2, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila10',
            field=models.CharField(max_length=5, verbose_name='fila10'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila11',
            field=models.CharField(max_length=5, verbose_name='fila11'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila12',
            field=models.CharField(max_length=5, verbose_name='fila12'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila13',
            field=models.CharField(max_length=5, verbose_name='fila13'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila14',
            field=models.CharField(max_length=5, verbose_name='fila14'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila20',
            field=models.CharField(max_length=5, verbose_name='fila20'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila21',
            field=models.CharField(max_length=5, verbose_name='fila21'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila22',
            field=models.CharField(max_length=5, verbose_name='fila22'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila23',
            field=models.CharField(max_length=5, verbose_name='fila23'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila24',
            field=models.CharField(max_length=5, verbose_name='fila24'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila30',
            field=models.CharField(max_length=5, verbose_name='fila30'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila31',
            field=models.CharField(max_length=5, verbose_name='fila31'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila32',
            field=models.CharField(max_length=5, verbose_name='fila32'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila33',
            field=models.CharField(max_length=5, verbose_name='fila34'),
        ),
        migrations.AlterField(
            model_name='carton',
            name='fila34',
            field=models.CharField(max_length=5, verbose_name='fila34'),
        ),
    ]
