# Generated by Django 3.1.6 on 2021-02-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0007_auto_20210214_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numeros_sorteados',
            old_name='valor',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='numeros_sorteados',
            name='celda',
        ),
    ]
