# Generated by Django 3.1.6 on 2021-02-17 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sorteo', '0008_auto_20210214_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carton',
            name='participante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
