# Generated by Django 3.1.6 on 2021-02-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0009_auto_20210216_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carton',
            name='fila10',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila11',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila12',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila13',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila14',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila20',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila21',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila22',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila23',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila24',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila30',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila31',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila32',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila33',
        ),
        migrations.RemoveField(
            model_name='carton',
            name='fila34',
        ),
        migrations.AddField(
            model_name='carton',
            name='fila1',
            field=models.CharField(default=None, max_length=500, verbose_name='fila10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carton',
            name='fila2',
            field=models.CharField(default=None, max_length=500, verbose_name='fila11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carton',
            name='fila3',
            field=models.CharField(default=None, max_length=500, verbose_name='fila12'),
            preserve_default=False,
        ),
    ]
