# Generated by Django 3.1.6 on 2021-02-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'get_latest_by': 'documento'},
        ),
    ]
